name: Node TypeScript Project Build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose Deployment Environment
        options:
          - dev
          - prod
jobs:
  pre-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello"
      - run: pwd
      - run: ls -l
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: NPM Install
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run build:${{ github.event.inputs.environment }}
      - run: ls -l
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: dist
          path: ./dist
      - name: ssh-scp-deploy
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          host: 143.198.195.139
          port: 22
          user: root
          key: ${{ secrets.DROPLET_KEY }}
          local: ./dist
          remote: /root/notification-service-node-ts
          pre_upload: pm2 stop notification_service
          post_upload: ls -l
          scp_options: -r -p
